version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_NAME}/site:/data/db
    ports:
      - "27017:27017"
  basketdb:
    container_name: basketdb
    restart: always    
    ports:
      - "6379:6379"
  rabbitmq:
    container_name: rabbitmq
    restart: always    
    ports:
      - "5672:5672"
      - "15672:15672"

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development      
      - "CatalogDatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    ports:
      - "8000:80"      
    depends_on:
      - catalogdb
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development      
      - "ConnectionStrings:Redis=basketdb:6379"
      - "EventBus:HostName=rabbitmq"
    ports:
      - "8001:80"      
    depends_on:
      - basketdb
      - rabbitmq
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
